title: El Mundo Digital
author: Sergio Serna
email: ignacio.serna@udea.edu.co
description: > # this means to ignore newlines until "baseurl:"
  Sitio maravillos, no lo encontrarás en ningún buscador.

# social links
twitter_username: sisernag # DO NOT include the @ character, or else the build will fail!
github_username:  sergioignacioserna # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
